name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Listar todos os arquivos do projeto
        run: ls -la

      - name: Transferir os arquivos para a VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app/**"       # tudo dentro de app/
          target: "/var/www/html"
          strip_components: 1    # descarta a pasta app/
          overwrite: true
